import { readFile, writeFile } from "node:fs/promises";
import { dirname, join } from "node:path";
import { createRequire } from "node:module";

const require = createRequire(import.meta.url);
const packages = [
  "react",
  "react-dom",
  "scheduler",
  "echarts",
  "zrender",
  "lucide-react",
  "zod",
  "tslib",
];
const notices = [
  "# Dashboard third-party notices\n\nGenerated by report-dashboard/scripts/write-notices.mjs. These libraries are bundled in dashboard.js.\n",
];
for (const name of packages) {
  const packagePath =
    name === "tslib"
      ? join(dirname(require.resolve(name)), "package.json")
      : require.resolve(`${name}/package.json`);
  const metadata = JSON.parse(await readFile(packagePath, "utf8"));
  const directory = dirname(packagePath);
  let license;
  for (const filename of ["LICENSE", "LICENSE.txt", "LICENSE.md"]) {
    try {
      license = await readFile(join(directory, filename), "utf8");
      break;
    } catch (error) {
      if (error.code !== "ENOENT") throw error;
    }
  }
  if (!license) throw new Error(`Missing license for ${name}`);
  notices.push(`## ${name} ${metadata.version}\n\n${license.trim()}\n`);
}
await writeFile(
  new URL(
    "../../codex-rs/report/assets/THIRD_PARTY_NOTICES.md",
    import.meta.url,
  ),
  notices.join("\n"),
);
