// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type AccountReadManyParams = {
/**
 * Account IDs to read. When omitted, all eligible persisted ChatGPT accounts are read.
 */
accountIds?: Array<string> | null, };
