// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { RateLimitResetCreditsSummary } from "./RateLimitResetCreditsSummary";
import type { RateLimitSnapshot } from "./RateLimitSnapshot";

export type AccountRateLimitsSnapshot = {
/**
 * Backend permission for ordinary included usage, validated against this account.
 * Null means unavailable; clients must not infer recovery from percentages or reset times.
 */
ordinaryUsageAllowed: boolean | null, rateLimits: RateLimitSnapshot, rateLimitsByLimitId: { [key in string]?: RateLimitSnapshot } | null, rateLimitResetCredits: RateLimitResetCreditsSummary | null, };
