// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Parameters for reading rate limits across persisted ChatGPT accounts.
 */
export type AccountRateLimitsReadManyParams = {
/**
 * Account IDs to read. When omitted, all eligible persisted ChatGPT accounts are read.
 */
accountIds?: Array<string> | null,
/**
 * Whether the requesting client supports automatic Luna Reserve fallback.
 */
supportsLunaReserve?: boolean,
/**
 * Skip reset-credit details for lightweight background polling.
 */
excludeResetCreditDetails?: boolean, };
