// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AccountRateLimitsSnapshot } from "./AccountRateLimitsSnapshot";
import type { ChatgptAccountSummary } from "./ChatgptAccountSummary";

export type AccountRateLimitsReadResult = { account: ChatgptAccountSummary, rateLimits: AccountRateLimitsSnapshot | null, error: string | null, };
