// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AccountTokenUsageSnapshot } from "./AccountTokenUsageSnapshot";
import type { ChatgptAccountSummary } from "./ChatgptAccountSummary";

export type AccountUsageReadResult = { account: ChatgptAccountSummary, usage: AccountTokenUsageSnapshot | null, error: string | null, };
